### ISSUE TITLE
[FR] 'Cycle bullet/checkbox' command

### ISSUE THREAD

**Issue by tadashi-aikawa** [roodolv/markdown-toggle.nvim#1]
Hi :)

Thank you for the wonderful plugin. It's very user-friendly, especially since I regularly use Obsidian.

I have assigned the 'Cycle bullet/checkbox' command to `Ctrl+Enter` in Obsidian. This command has a somewhat unique behavior as described below.

```
hoge
↓
- hoge
↓
- [ ] hoge
↓
- [x] hoge
↓
- hoge
↓
- [ ] hoge
↓
- [x] hoge
↓
- hoge
↓
.
.
```

I would appreciate it if you could consider this.

**Comment by roodolv** [comment]
Hello. Thanks for using this plugin.
I am honored that you are satisfied with it.

---

If I implement that feature, I'll probably add some config options as shown below.
Let me know if this looks good to you.

### Case1. Mimicking Obsidian's 'Cycle bullet/checkbox'
```lua
require("markdown-toggle").setup({
  enable_box_cycle_obsidian = true, -- new option
  enable_box_cycle = true,
  box_table = { "x" }, 
})
```

In this case, the cycle would look like this:
```txt
hoge
↓
- hoge
↓
- [ ] hoge
↓
- [x] hoge
↓
- hoge
↓
- [ ] hoge
↓
```

### Case2. In case of various markup cycles in addition to above
```lua
require("markdown-toggle").setup({
  enable_box_cycle_obsidian = true, -- new option
  enable_box_cycle = true,
  box_table = { "x", "~", "!" }, -- for cycling between various states
})
```

Here's how the cycle would work:
```txt
hoge
↓
- hoge
↓
- [ ] hoge
↓
- [x] hoge
↓
- [~] hoge
↓
- [!] hoge
↓
- hoge
↓
- [ ] hoge
↓
```

### Case3. If you don't want to use the new feature
```lua
require("markdown-toggle").setup({
  enable_box_cycle_obsidian = false, -- new option
  enable_box_cycle = true,
  box_table = { "x" }, 
})
```

In this case, the cycle would be like this (same as the current toggle command):
```txt
hoge
↓
- [ ] hoge
↓
- [x] hoge
↓
- [ ] hoge
↓
```

In addition, I'm planning to add a NEW config option for 'list' as well.
This will allow for more Obsidian-like behavior in areas where the current functionality differs from Obsidian.

**Comment by roodolv** [comment]
I've just implemented the Mimicking Obsidian feature: https://github.com/roodolv/markdown-toggle.nvim/commit/4daa99172415a075866deac738c9e24a94a4b238

Please check the latest commit.
Sorry for not versioning. (I'll do it later.)
I would appreciate any feedback or reactions.

**Comment by tadashi-aikawa** [comment]
@roodolv 
Thank you for your prompt response! I have confirmed that it works as expected with the following settings. It looks like Markdown editing in Neovim will be much more efficient 😊

```
{
  "roodolv/markdown-toggle.nvim",
  branch = "main",
  config = function()
    require("markdown-toggle").setup({
      enable_box_cycle = true,
      box_table = { "x" },
    })

    vim.api.nvim_create_autocmd("FileType", {
      desc = "markdown-toggle.nvim keymaps",
      pattern = { "markdown", "markdown.mdx" },
      callback = function(args)
        local opts = { silent = true, noremap = true, buffer = args.buf }
        local toggle = require("markdown-toggle")

        -- F12はCtrl+Enter
        vim.keymap.set({ "n", "v" }, "<F12>", toggle.checkbox, opts)
      end,
    })
  end,
}
```

**Comment by roodolv** [comment]
I'm glad to hear that.
Thanks.
